// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgBty5r9_hTSqMF3KbSkj3-nFvNcWkdP8',
    appId: '1:19873536274:web:074ea836e0869a6ff2bbcb',
    messagingSenderId: '19873536274',
    projectId: 'poytug-gtk',
    authDomain: 'poytug-gtk.firebaseapp.com',
    storageBucket: 'poytug-gtk.firebasestorage.app',
    measurementId: 'G-FPHKV73ZE2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFETAN_syHH5L7Py611sFjX_LJPUIkM_o',
    appId: '1:19873536274:android:844eced5cd03e9f9f2bbcb',
    messagingSenderId: '19873536274',
    projectId: 'poytug-gtk',
    storageBucket: 'poytug-gtk.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAaDXTpJ9qmEzv8vTNbDe8hSeJPNBoZk4',
    appId: '1:19873536274:ios:9c04269bae76ae82f2bbcb',
    messagingSenderId: '19873536274',
    projectId: 'poytug-gtk',
    storageBucket: 'poytug-gtk.firebasestorage.app',
    iosBundleId: 'com.example.poytugGtk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAaDXTpJ9qmEzv8vTNbDe8hSeJPNBoZk4',
    appId: '1:19873536274:ios:9c04269bae76ae82f2bbcb',
    messagingSenderId: '19873536274',
    projectId: 'poytug-gtk',
    storageBucket: 'poytug-gtk.firebasestorage.app',
    iosBundleId: 'com.example.poytugGtk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgBty5r9_hTSqMF3KbSkj3-nFvNcWkdP8',
    appId: '1:19873536274:web:369de00d7fbe32fff2bbcb',
    messagingSenderId: '19873536274',
    projectId: 'poytug-gtk',
    authDomain: 'poytug-gtk.firebaseapp.com',
    storageBucket: 'poytug-gtk.firebasestorage.app',
    measurementId: 'G-EFV2X02VBS',
  );

}